const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DATA_FILE = path.join(ROOT, "data", "tools.json");
const README_FILE = path.join(ROOT, "README.md");
const DOCS_DIR = path.join(ROOT, "docs");
const INDEX_FILE = path.join(DOCS_DIR, "index.html");

const data = JSON.parse(fs.readFileSync(DATA_FILE, "utf8"));

if (!data.title || !Array.isArray(data.categories) || data.categories.length === 0) {
  console.error("Invalid data/tools.json: missing title or categories.");
  process.exit(1);
}

const categories = data.categories.map((cat) => {
  if (!cat.id || !cat.name || !Array.isArray(cat.tools)) {
    console.error(`Invalid category in data/tools.json: ${JSON.stringify(cat)}`);
    process.exit(1);
  }
  return cat;
});

const totalTools = categories.reduce((sum, cat) => sum + cat.tools.length, 0);
const freeTierCount = categories.reduce(
  (sum, cat) => sum + cat.tools.filter((t) => t.access && t.access !== "free").length,
  0
);

function slugify(str) {
  return str
    .toLowerCase()
    .replace(/<[^>]+>/g, "")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s-]+/g, "-");
}

function accessLabel(tool) {
  if (tool.access && tool.access !== "free") return "⚠️ Free tier";
  return "✅ Free";
}

function buildReadme() {
  const toc = categories
    .map((cat) => `- [${cat.icon} ${cat.name}](#${slugify(cat.name)})`)
    .join("\n");

  const sections = categories
    .map((cat) => {
      const rows = cat.tools
        .map(
          (tool) =>
            `| [${tool.name}](${tool.url}) | ${tool.description}${
              tool.note ? ` _(${tool.note})_` : ""
            } | ${tool.tags.map((t) => `\`${t}\``).join(" · ")} | ${accessLabel(tool)} |`
        )
        .join("\n");

      return `## ${cat.icon} ${cat.name}\n\n> ${cat.description}\n\n| Tool | Description | Tags | Access |\n| :--- | :--- | :--- | :--- |\n${rows}`;
    })
    .join("\n\n---\n\n");

  return `<!--
  ⚠️ AUTO-GENERATED FILE — do not edit directly.
  Edit data/tools.json and run: npm run build
-->

<div align="center">

# 🛡️ SOC Tools

**${data.tagline}**

![Tools](https://img.shields.io/badge/Tools-${totalTools}-2ea44f)
![Categories](https://img.shields.io/badge/Categories-${categories.length}-2ea44f)
[![License: GPL-3.0](https://img.shields.io/badge/License-GPL--3.0-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)

> 🌐 Browse the interactive, searchable version: **https://samunoske.github.io/SOC-Tools** ·
> ⚠️ Items marked **Free tier** offer a free account tier with usage limits or trial-based access.

</div>

## 📑 Table of Contents

${toc}

---

${sections}

---

## ➕ Adding a Tool

1. Add or update an entry in [\`data/tools.json\`](data/tools.json).
2. Run \`npm run build\` to regenerate \`README.md\` and \`docs/index.html\`.
3. Open a pull request.

## 📜 License

[GPL-3.0](LICENSE)

---

<div align="center">

**${totalTools} tools** · **${categories.length} categories** · ${freeTierCount} with limited/free-tier access

Generated by [\`scripts/build.js\`](scripts/build.js) from [\`data/tools.json\`](data/tools.json)

</div>
`;
}

function escHtml(str) {
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function buildHtml() {
  const embedded = JSON.stringify(data).replace(/</g, "\\u003c");
  const catJson = JSON.stringify(categories).replace(/</g, "\\u003c");

  const chips = categories
    .map((cat) => `<button class="chip" data-cat="${cat.id}">${cat.icon} ${escHtml(cat.name)}</button>`)
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escHtml(data.title)} — Free &amp; Open-Source Security Tools</title>
<meta name="description" content="${escHtml(data.tagline)}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🛡️</text></svg>">
<style>
:root{--bg:#0a0e17;--surface:#111726;--border:#1e293b;--text:#e2e8f0;--muted:#8b98ab;--accent:#22d3ee;--accent2:#34d399;--warn:#fbbf24;--radius:12px}
*{box-sizing:border-box;margin:0;padding:0}
body{background:radial-gradient(1200px 600px at 50% -10%,#12203a 0%,var(--bg) 55%) fixed;color:var(--text);font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.55;min-height:100vh}
.wrap{max-width:1100px;margin:0 auto;padding:0 24px}
a{color:var(--accent)}
header{padding:56px 0 8px;text-align:center}
.shell{font-size:46px;line-height:1}
h1{font-size:40px;letter-spacing:-0.5px;margin:12px 0 6px}
.tagline{color:var(--muted);max-width:680px;margin:0 auto 24px;font-size:17px}
.stats{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}
.stat{background:var(--surface);border:1px solid var(--border);border-radius:999px;padding:8px 18px;font-size:14px;color:var(--muted)}
.stat b{color:var(--accent)}
.controls{position:sticky;top:0;z-index:10;padding:22px 0;background:linear-gradient(180deg,rgba(10,14,23,.95),rgba(10,14,23,.7) 70%,rgba(10,14,23,0));backdrop-filter:blur(6px)}
#search{width:100%;padding:14px 18px;font-size:16px;border-radius:var(--radius);border:1px solid var(--border);background:var(--surface);color:var(--text);outline:none;transition:border-color .15s}
#search:focus{border-color:var(--accent)}
#search::placeholder{color:#5b6b80}
.chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}
.chip{border:1px solid var(--border);background:var(--surface);color:var(--muted);padding:7px 14px;border-radius:999px;font-size:13px;cursor:pointer;transition:all .15s;font-family:inherit}
.chip:hover{border-color:var(--accent);color:var(--text)}
.chip.active{background:var(--accent);border-color:var(--accent);color:#06202a;font-weight:600}
.category{padding:28px 0 8px}
.category h2{font-size:22px;display:flex;align-items:center;gap:10px;border-bottom:1px solid var(--border);padding-bottom:10px;scroll-margin-top:120px}
.count{font-size:13px;color:var(--muted);font-weight:400;margin-left:auto;background:var(--surface);border:1px solid var(--border);border-radius:999px;padding:2px 10px}
.cat-desc{color:var(--muted);font-size:14px;margin:8px 0 16px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:18px;display:flex;flex-direction:column;gap:10px;transition:border-color .15s,transform .15s}
.card:hover{border-color:var(--accent);transform:translateY(-2px)}
.card h3{font-size:16px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.card h3 a{color:var(--text);text-decoration:none}
.card h3 a:hover{color:var(--accent)}
.ext{color:var(--muted);font-size:12px}
.badge{font-size:11px;font-weight:600;color:#06202a;background:var(--warn);border-radius:999px;padding:2px 8px;cursor:help}
.desc{color:var(--muted);font-size:14px;flex:1}
.note{font-size:12px;color:var(--warn)}
.tags{display:flex;flex-wrap:wrap;gap:6px}
.tags code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:var(--accent2);background:rgba(52,211,153,.08);border:1px solid rgba(52,211,153,.2);padding:2px 7px;border-radius:6px}
.noresults{display:none;text-align:center;color:var(--muted);padding:60px 0}
footer{padding:40px 0 56px;text-align:center;color:var(--muted);font-size:13px;border-top:1px solid var(--border);margin-top:40px}
footer a{text-decoration:none}
footer a:hover{text-decoration:underline}
@media (max-width:640px){header{padding-top:40px}h1{font-size:32px}}
</style>
</head>
<body>
<header>
  <div class="shell">🛡️</div>
  <h1>${escHtml(data.title)}</h1>
  <p class="tagline">${escHtml(data.tagline)}</p>
  <div class="stats">
    <span class="stat"><b>${totalTools}</b> tools</span>
    <span class="stat"><b>${categories.length}</b> categories</span>
    <span class="stat"><b>${freeTierCount}</b> with free tiers</span>
  </div>
</header>

<main class="wrap">
  <div class="controls">
    <input id="search" type="search" placeholder="Search tools, descriptions, tags… (press / to focus)" autocomplete="off" aria-label="Search tools">
    <div id="chips" class="chips" role="tablist" aria-label="Filter by category">${chips}</div>
  </div>
  <div id="content"></div>
  <div id="noresults" class="noresults">No tools match your search. 🕵️</div>
</main>

<footer class="wrap">
  Generated by <a href="https://github.com/samunoske/SOC-Tools/blob/main/scripts/build.js">scripts/build.js</a> from
  <a href="https://github.com/samunoske/SOC-Tools/blob/main/data/tools.json">data/tools.json</a> ·
  <a href="https://github.com/samunoske/SOC-Tools">View source on GitHub</a>
</footer>

<script type="application/json" id="tools-data">${embedded}</script>
<script>
const CATS = ${catJson};
const contentEl = document.getElementById('content');
const searchEl = document.getElementById('search');
const chipsEl = document.getElementById('chips');
const noresultsEl = document.getElementById('noresults');
let activeCat = 'all';
let query = '';

function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}

function matches(tool){
  const q = query.trim().toLowerCase();
  if(!q) return true;
  const hay = (tool.name + ' ' + (tool.description||'') + ' ' + (tool.tags||[]).join(' ')).toLowerCase();
  return q.split(/\\s+/).every(w => hay.includes(w));
}

function card(tool){
  const limited = tool.access && tool.access !== 'free';
  const badge = limited ? '<span class="badge" title="' + esc(tool.note || 'Limited free tier / trial-based access') + '">⚠️ Free tier</span>' : '';
  const note = limited && tool.note ? '<div class="note">' + esc(tool.note) + '</div>' : '';
  return '<article class="card">' +
    '<h3><a href="' + esc(tool.url) + '" target="_blank" rel="noopener noreferrer">' + esc(tool.name) + ' <span class="ext">↗</span></a>' + badge + '</h3>' +
    '<p class="desc">' + esc(tool.description || '') + '</p>' +
    note +
    '<div class="tags">' + (tool.tags||[]).map(t => '<code>' + esc(t) + '</code>').join('') + '</div>' +
    '</article>';
}

function render(){
  document.querySelectorAll('.chip').forEach(chip => chip.classList.toggle('active', chip.dataset.cat === activeCat));
  const cats = CATS.filter(c => activeCat === 'all' || c.id === activeCat);
  let html = '', visible = 0;
  for(const cat of cats){
    const tools = cat.tools.filter(matches);
    if(!tools.length) continue;
    visible += tools.length;
    html += '<section class="category" id="' + cat.id + '">' +
      '<h2>' + cat.icon + ' ' + esc(cat.name) + '<span class="count">' + tools.length + (tools.length !== cat.tools.length ? ' / ' + cat.tools.length : '') + '</span></h2>' +
      '<p class="cat-desc">' + esc(cat.description || '') + '</p>' +
      '<div class="grid">' + tools.map(card).join('') + '</div>' +
      '</section>';
  }
  contentEl.innerHTML = html;
  noresultsEl.style.display = visible ? 'none' : 'block';
}

searchEl.addEventListener('input', e => { query = e.target.value; render(); });
chipsEl.addEventListener('click', e => {
  const chip = e.target.closest('button.chip');
  if(!chip) return;
  activeCat = chip.dataset.cat;
  render();
});
document.addEventListener('keydown', e => {
  if(e.key === '/' && document.activeElement !== searchEl){
    e.preventDefault();
    searchEl.focus();
  }
});

render();
</script>
</body>
</html>
`;
}

fs.mkdirSync(DOCS_DIR, { recursive: true });
fs.writeFileSync(README_FILE, buildReadme());
fs.writeFileSync(INDEX_FILE, buildHtml());

console.log(`✓ Generated README.md (${totalTools} tools, ${categories.length} categories, ${freeTierCount} free-tier)`);
console.log(`✓ Generated docs/index.html`);
